[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_port = ${env:esp32dev.upload_port}
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0

monitor_dtr = 0
monitor_rts = 0

extra_scripts = scripts/after_upload.py
custom_post_upload_delay = 2.8

build_flags =
  -I .pio/libdeps/${PIOENV}/arduino_keypads
  -I .pio/libdeps/${PIOENV}/arduino_keypads/Keypad_I2C

lib_deps =
  Keypad@^3.1.1
  RobTillaart/Keypad_I2C    ; <- ไลบรารี I2C ล้วน ๆ
  miguelbalboa/MFRC522@^1.4.11
  adafruit/Adafruit GFX Library@^1.11.10
  adafruit/Adafruit SSD1306@^2.5.7
  ricmoo/QRCode@^0.0.1
  https://github.com/johnrickman/LiquidCrystal_I2C.git

lib_ldf_mode = deep+
