[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_port = ${env:esp32dev.upload_port}
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0

; monitor_dtr = 0
; monitor_rts = 0

extra_scripts = scripts/after_upload.py
custom_post_upload_delay = 2.8

lib_deps =
  Keypad@^3.1.1
  miguelbalboa/MFRC522
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  ricmoo/QRCode
  https://github.com/johnrickman/LiquidCrystal_I2C

lib_ldf_mode = deep+
