[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_port = ${env:esp32dev.upload_port}
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.3
    adafruit/Adafruit SSD1306@^2.5.7
    ricmoo/QRCode @ ^0.0.1

lib_ldf_mode = deep+

extra_scripts = scripts/after_upload.py
custom_post_upload_delay = 2.8
